// <auto-generated />
namespace N01516955_Proposal_Project1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changeAppointmentKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeAppointmentKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202206010004320_changeAppointmentKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
